version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: J@y1312
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: inventory_backend
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: J@y1312
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: inventory_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  